# Generated by Django 3.1.6 on 2021-04-16 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heavenview', '0002_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='type',
        ),
    ]
