# Generated by Django 3.1.6 on 2021-04-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heavenview', '0004_auto_20210416_1026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserve',
        ),
    ]
