# Generated by Django 3.1.6 on 2021-04-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heavenview', '0006_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='date',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='roomcode',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
