# Generated by Django 3.1.6 on 2021-04-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heavenview', '0007_auto_20210416_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='roomcode',
            field=models.TextField(max_length=5, null=True),
        ),
    ]
