# Generated by Django 3.1.6 on 2021-04-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heavenview', '0008_auto_20210416_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='roomcode',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
