# Generated by Django 3.1.6 on 2021-04-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heavenview', '0009_auto_20210417_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
