# Generated by Django 3.1.6 on 2021-04-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heavenview', '0011_auto_20210417_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
